name: cuda_blob
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - appdirs=1.4.4
  - binutils=2.35.1
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-compiler=1.1.3
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - charls=2.2.0
  - cloudpickle=1.6.0
  - compilers=1.1.3
  - cryptography=3.3.1
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - cupy=8.3.0
  - cxx-compiler=1.1.3
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask-core=2021.1.0
  - decorator=4.4.2
  - fastrlock=0.5
  - fortran-compiler=1.1.3
  - freetype=2.10.4
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - giflib=5.2.1
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - idna=2.10
  - imagecodecs=2021.1.11
  - imageio=2.9.0
  - jpeg=9d
  - jxrlib=1.1
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libzopfli=1.0.3
  - llvm-openmp=8.0.1
  - llvmlite=0.35.0
  - lz4-c=1.9.2
  - matplotlib-base=3.3.3
  - mpi=1.0
  - nccl=2.8.3.1
  - ncurses=6.2
  - networkx=2.5
  - numba=0.52.0
  - numpy=1.19.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openmp=8.0.1
  - openmpi=4.0.5
  - openmpi-mpicc=4.0.5
  - openssl=1.1.1i
  - packaging=20.8
  - pillow=8.0.1
  - pooch=1.3.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pywavelets=1.1.1
  - readline=8.0
  - requests=2.25.1
  - scikit-image=0.18.1
  - scipy=1.6.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.34.0
  - sysroot_linux-64=2.17
  - tifffile=2021.1.14
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - urllib3=1.26.2
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - alembic==1.4.3
    - attrs==20.3.0
    - cliff==3.5.0
    - cmaes==0.7.0
    - cmd2==1.4.0
    - colorama==0.4.4
    - colorlog==4.6.2
    - filelock==3.0.12
    - joblib==1.0.0
    - mako==1.1.3
    - markupsafe==1.1.1
    - mpi4py==3.1.0a0
    - nvidia-dali-cuda110==0.30.0
    - optuna==2.3.0
    - pandas==1.2.2
    - pbr==5.5.1
    - pip==21.0.1
    - prettytable==0.7.2
    - protobuf==3.14.0
    - py3nvml==0.2.6
    - pydevd-pycharm==203.6682.179
    - pyperclip==1.8.1
    - python-editor==1.0.4
    - pytz==2021.1
    - pyyaml==5.3.1
    - setuptools==53.1.0
    - sqlalchemy==1.3.22
    - stevedore==3.3.0
    - tikzplotlib==0.9.8
    - tqdm==4.55.0
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - xmltodict==0.12.0
